name: pipeline
on: 
  push:
  workflow_dispatch:

jobs:
  actions-test:
    runs-on: ubuntu-latest
    name: actions-test
    steps:
      - uses: actions/checkout@v4
      - id: step-id
        uses: tiggus/actions-library/action@main
        with:
          string: 'actions-test-string'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.step-id.outputs.random-number }}

  build-test-deploy:
    uses: tiggus/workflows/.github/workflows/node.yaml@main
    with:
      node-version: '18.x'
      envname: 'dev'
  
  upload-artifact:
    uses: tiggus/workflows/.github/workflows/artifact.yaml@main
    with:
      artifact-name: 'artifact'
      artifact-path: 'output'
