on: [push]

jobs:
  actions_test:
    runs-on: ubuntu-latest
    name: actions_test
    steps:
      - uses: actions/checkout@v4
      - id: step-id
        uses: tiggus/actions-library/action@main
        with:
          string: 'actions-test-string'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.step-id.outputs.random-number }}

  call-workflow-passing-data:
    uses: tiggus/workflows/.github/workflows/workflow.yaml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      personal_access_token: ${{ secrets.TOKEN }}